#!/bin/bash

DATE=$(date "+%Y-%m-%d")
TIME=$(date "+%H:%M:%S")
FILENAME=`sed 's/ /-/g' <<< "$@"`
FILENAME="$DATE-$FILENAME.md"
echo "---" >> _posts/"$FILENAME"
echo "layout: post" >> _posts/"$FILENAME"
echo "title: $@" >> _posts/"$FILENAME"
echo "date: $DATE $TIME" >> _posts/"$FILENAME"
echo "---" >> _posts/"$FILENAME"
vim _posts/"$FILENAME"
